/**
 * Server-Side Admin Authentication — Production Security & Infrastructure
 *
 * Replaces the insecure client-side sessionStorage auth with proper
 * HttpOnly cookie-based authentication.
 *
 * Architecture:
 * - Login: POST /api/admin/auth/login → server compares password → sets HttpOnly cookie
 * - Logout: POST /api/admin/auth/logout → server clears cookie
 * - Verification: Every admin API route checks the HttpOnly cookie
 *
 * Cookie-based session token:
 * - Token = HMAC-SHA256(timestamp + nonce, ADMIN_SECRET)
 * - The secret is derived from ADMIN_PASSWORD (not exposed to browser)
 * - Token expires after 24 hours
 * - HttpOnly, Secure, SameSite=Strict, Path=/api/admin
 *
 * No external dependencies required — uses Node.js built-in crypto.
 */

import { cookies } from 'next/headers';
import { createHmac, randomBytes, timingSafeEqual } from 'crypto';

// ============================================================================
// CONFIGURATION
// ============================================================================

const SESSION_DURATION_HOURS = 24;
const SESSION_DURATION_MS = SESSION_DURATION_HOURS * 60 * 60 * 1000;
const COOKIE_NAME = 'tikdl_admin_session';

// ============================================================================
// TOKEN GENERATION & VERIFICATION
// ============================================================================

/**
 * Derive a signing secret from the admin password.
 * This secret is NEVER exposed to the browser — it stays server-side only.
 */
function getSigningSecret(): string {
  const adminPassword = process.env.ADMIN_PASSWORD;
  if (!adminPassword) {
    if (process.env.NODE_ENV === 'production') {
      throw new Error('[Auth] ADMIN_PASSWORD must be set in production. Refusing to start with insecure fallback.');
    }
    console.warn('[Auth] ADMIN_PASSWORD env var not set. Using development fallback — NOT production-safe.');
    return 'dev-only-fallback-secret-change-in-production';
  }
  return adminPassword;
}

/**
 * Generate a signed session token.
 * Token format: timestamp.nonce.hmac
 * - timestamp: milliseconds since epoch (for expiry checking)
 * - nonce: random hex string (for uniqueness)
 * - hmac: HMAC-SHA256(timestamp + "." + nonce, secret)
 */
function generateToken(): string {
  const timestamp = Date.now();
  const nonce = randomBytes(16).toString('hex');
  const message = `${timestamp}.${nonce}`;
  const hmac = createHmac('sha256', getSigningSecret()).update(message).digest('hex');
  return `${message}.${hmac}`;
}

/**
 * Verify a session token.
 * Returns true if:
 * - The HMAC signature is valid (token was generated by our server)
 * - The timestamp is within the session duration (not expired)
 */
function verifyToken(token: string): boolean {
  const parts = token.split('.');
  if (parts.length !== 3) return false;

  const [timestampStr, nonce, providedHmac] = parts;
  const timestamp = parseInt(timestampStr, 10);

  // Check expiry
  if (Date.now() - timestamp > SESSION_DURATION_MS) return false;

  // Check HMAC signature
  const message = `${timestampStr}.${nonce}`;
  const expectedHmac = createHmac('sha256', getSigningSecret()).update(message).digest('hex');

  // Use timing-safe comparison to prevent timing attacks
  try {
    return timingSafeEqual(
      Buffer.from(providedHmac, 'hex'),
      Buffer.from(expectedHmac, 'hex')
    );
  } catch {
    // Length mismatch or invalid hex — reject
    return false;
  }
}

// ============================================================================
// AUTHENTICATION FUNCTIONS
// ============================================================================

/**
 * Verify admin password against the server-side ADMIN_PASSWORD env var.
 * This function NEVER exposes the password to the client.
 */
export function verifyAdminPassword(providedPassword: string): boolean {
  const adminPassword = process.env.ADMIN_PASSWORD;
  if (!adminPassword) {
    if (process.env.NODE_ENV === 'production') {
      // In production without ADMIN_PASSWORD, ALL login attempts must fail
      console.error('[Auth] ADMIN_PASSWORD not configured in production. Rejecting all login attempts.');
      return false;
    }
    // In development without ADMIN_PASSWORD set, allow 'admin123' for convenience
    console.warn('[Auth] ADMIN_PASSWORD not configured. Using development fallback.');
    return providedPassword === 'admin123';
  }

  // Timing-safe comparison to prevent timing attacks
  try {
    return timingSafeEqual(
      Buffer.from(providedPassword),
      Buffer.from(adminPassword)
    );
  } catch {
    // Length mismatch — reject immediately
    return false;
  }
}

/**
 * Set the admin session cookie on successful login.
 * Returns true on success.
 */
export async function setAdminSession(): Promise<boolean> {
  const token = generateToken();
  const cookieStore = await cookies();

  cookieStore.set(COOKIE_NAME, token, {
    httpOnly: true,     // Never accessible from JavaScript
    secure: process.env.NODE_ENV === 'production',  // HTTPS only in production
    sameSite: 'strict', // CSRF protection
    path: '/api',        // Cookie sent to all API routes (includes /api/admin and /api/analytics)
    maxAge: SESSION_DURATION_HOURS * 3600, // 24 hours
  });

  return true;
}

/**
 * Clear the admin session cookie on logout.
 */
export async function clearAdminSession(): Promise<void> {
  const cookieStore = await cookies();
  cookieStore.delete(COOKIE_NAME);
}

/**
 * Verify that the current request has a valid admin session.
 * Used by all admin API routes as an authentication guard.
 *
 * Returns true if the session is valid, false otherwise.
 */
export async function isAuthenticated(): Promise<boolean> {
  const cookieStore = await cookies();
  const token = cookieStore.get(COOKIE_NAME)?.value;

  if (!token) return false;
  return verifyToken(token);
}

/**
 * Require authentication — returns a NextResponse error if not authenticated.
 * Use this as a guard in admin API routes:
 *
 *   const authError = requireAuth();
 *   if (authError) return authError;
 */
export async function requireAuth(): Promise<Response | null> {
  const authenticated = await isAuthenticated();
  if (!authenticated) {
    return new Response(
      JSON.stringify({ success: false, error: 'Authentication required' }),
      {
        status: 401,
        headers: { 'Content-Type': 'application/json' },
      }
    );
  }
  return null;
}

