/**
 * NovaDL Engine — Core Type Definitions
 * 
 * Every component in the engine references these types.
 * They define the contracts between providers, the pipeline,
 * the plugin system, the API, and all supporting infrastructure.
 */

// ─── Platform ────────────────────────────────────────────────────
export type Platform =
  | 'tiktok'
  | 'instagram'
  | 'facebook'
  | 'youtube'
  | 'youtube_shorts'
  | 'x_twitter'
  | 'pinterest'
  | 'threads'
  | 'snapchat_spotlight'
  | 'reddit'
  | 'linkedin'
  | 'vimeo'
  | 'dailymotion'
  | 'likee'
  | 'bilibili'
  | 'capcut'
  | 'soundcloud'
  | 'spotify'
  | 'lemon8'
  | 'tumblr'
  | 'streamable'
  | 'vk'
  | 'mixcloud'
  | 'unknown';

export const PLATFORM_DETECTORS: Record<string, Platform> = {
  'tiktok.com': 'tiktok',
  'vm.tiktok.com': 'tiktok',
  'instagram.com': 'instagram',
  'facebook.com': 'facebook',
  'fb.watch': 'facebook',
  'youtube.com': 'youtube',
  'youtu.be': 'youtube',
  'x.com': 'x_twitter',
  'twitter.com': 'x_twitter',
  't.co': 'x_twitter',
  'pinterest.com': 'pinterest',
  'threads.net': 'threads',
  'snapchat.com': 'snapchat_spotlight',
  'reddit.com': 'reddit',
  'linkedin.com': 'linkedin',
  'vimeo.com': 'vimeo',
  'dailymotion.com': 'dailymotion',
  'likee.video': 'likee',
  'bilibili.com': 'bilibili',
  'b23.tv': 'bilibili',
  'capcut.com': 'capcut',
  'soundcloud.com': 'soundcloud',
  'spotify.com': 'spotify',
  'open.spotify.com': 'spotify',
  'lemon8.com': 'lemon8',
  'tumblr.com': 'tumblr',
  'streamable.com': 'streamable',
  'vk.com': 'vk',
  'm.vk.com': 'vk',
  'mixcloud.com': 'mixcloud',
};

// ─── Media Format ────────────────────────────────────────────────
export type VideoFormat = 'mp4' | 'webm' | 'avi' | 'mov' | 'flv';
export type AudioFormat = 'mp3' | 'aac' | 'opus' | 'flac' | 'wav' | 'm4a' | 'ogg';
export type ImageFormat = 'png' | 'jpeg' | 'webp' | 'gif';
export type SubtitleFormat = 'srt' | 'vtt' | 'ass' | 'lrc';

export type MediaFormat = VideoFormat | AudioFormat | ImageFormat | SubtitleFormat;

export type MediaType = 'video' | 'audio' | 'image' | 'subtitle' | 'metadata';

// ─── Quality ──────────────────────────────────────────────────────
export type VideoQuality = 
  | '2160p'   // 4K
  | '1440p'   // 2K
  | '1080p'   // Full HD
  | '720p'    // HD
  | '480p'    // SD
  | '360p'    // Low
  | '240p'    // Very low
  | 'best'    // Highest available
  | 'worst'   // Lowest available
  | string;   // Custom quality labels

export type AudioQuality = 
  | '320kbps'
  | '256kbps'
  | '192kbps'
  | '128kbps'
  | '96kbps'
  | '64kbps'
  | 'best'
  | 'worst'
  | string;

export interface Resolution {
  width: number;
  height: number;
}

export interface CodecInfo {
  video?: string;    // e.g., 'h264', 'h265', 'vp9', 'av1'
  audio?: string;    // e.g., 'aac', 'opus', 'mp3', 'flac'
  container?: string; // e.g., 'mp4', 'webm', 'mkv'
}

// ─── Extraction Result ────────────────────────────────────────────
export interface ExtractionResult {
  id: string;
  url: string;
  platform: Platform;
  provider: string;
  timestamp: Date;
  media: MediaItem[];
  metadata: ExtractionMetadata;
  subtitles?: SubtitleTrack[];
  covers?: CoverImage[];
  thumbnails?: Thumbnail[];
  qualityOptions?: QualityOption[];
  rawResponse?: unknown;
}

export interface MediaItem {
  type: MediaType;
  format: MediaFormat;
  quality: VideoQuality | AudioQuality;
  url: string;
  directUrl?: string;
  streamUrl?: string;
  localPath?: string;
  size?: number;
  duration?: number;
  bitrate?: number;
  codec?: CodecInfo;
  resolution?: Resolution;
  fps?: number;
  watermark?: WatermarkInfo;
  title?: string;
  description?: string;
  filename?: string;
  headers?: Record<string, string>;
}

export interface ExtractionMetadata {
  title?: string;
  description?: string;
  author?: string;
  authorId?: string;
  authorUrl?: string;
  platform: Platform;
  originalUrl?: string;
  duration?: number;
  viewCount?: number;
  likeCount?: number;
  commentCount?: number;
  shareCount?: number;
  uploadDate?: string;
  categories?: string[];
  tags?: string[];
  isLive?: boolean;
  isPrivate?: boolean;
  ageRestricted?: boolean;
  extra?: Record<string, unknown>;
}

export interface SubtitleTrack {
  language: string;
  languageCode: string;
  format: SubtitleFormat;
  url?: string;
  content?: string;
  autoGenerated?: boolean;
}

export interface CoverImage {
  url: string;
  width?: number;
  height?: number;
  format: ImageFormat;
  localPath?: string;
}

export interface Thumbnail {
  url: string;
  width?: number;
  height?: number;
  format: ImageFormat;
  localPath?: string;
}

export interface QualityOption {
  label: string;
  quality: VideoQuality | AudioQuality;
  format: MediaFormat;
  size?: number;
  codec?: CodecInfo;
  resolution?: Resolution;
  bitrate?: number;
  url?: string;
  isSource?: boolean;
}

export interface WatermarkInfo {
  detected: boolean;
  position?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center' | 'overlay';
  removable?: boolean;
  removed?: boolean;
  description?: string;
}

// ─── Provider ──────────────────────────────────────────────────────
export type ProviderStatus = 'healthy' | 'degraded' | 'unhealthy' | 'unknown' | 'disabled';

export type ProviderType = 'api' | 'cli' | 'custom';

export interface ProviderHealth {
  status: ProviderStatus;
  latencyMs?: number;
  successRate?: number;
  lastChecked?: Date;
  lastError?: string;
  consecutiveFailures?: number;
  consecutiveSuccesses?: number;
  uptime?: number;
}

export interface ProviderConfig {
  id: string;
  name: string;
  type: ProviderType;
  enabled: boolean;
  priority: number;
  timeout: number;
  maxRetries: number;
  platforms: Platform[];
  apiKey?: string;
  baseUrl?: string;
  customOptions?: Record<string, unknown>;
}

export interface ProviderCapabilities {
  platforms: Platform[];
  mediaTypes: MediaType[];
  formats: MediaFormat[];
  qualities: (VideoQuality | AudioQuality)[];
  features: ProviderFeature[];
  maxConcurrent: number;
}

export type ProviderFeature =
  | 'video_download'
  | 'audio_download'
  | 'cover_extraction'
  | 'thumbnail_extraction'
  | 'metadata_extraction'
  | 'subtitle_extraction'
  | 'watermark_detection'
  | 'watermark_removal'
  | 'streaming'
  | 'multiple_qualities'
  | 'codec_detection'
  | 'live_stream'
  | 'playlist'
  | 'stories'
  | 'reels';

export interface ExtractionRequest {
  url: string;
  platform?: Platform;
  options?: ExtractionOptions;
  preferredProvider?: string;
  preferredQuality?: VideoQuality | AudioQuality;
  preferredFormat?: MediaFormat;
}

export interface ExtractionOptions {
  extractVideo?: boolean;
  extractAudio?: boolean;
  extractCover?: boolean;
  extractThumbnail?: boolean;
  extractMetadata?: boolean;
  extractSubtitles?: boolean;
  extractAllQualities?: boolean;
  detectWatermark?: boolean;
  removeWatermark?: boolean;
  timeout?: number;
  maxRetries?: number;
  noFallback?: boolean;
  noCache?: boolean;
  stream?: boolean;
  formats?: MediaFormat[];
  qualities?: (VideoQuality | AudioQuality)[];
  languages?: string[];
}

// ─── Pipeline ──────────────────────────────────────────────────────
export type PipelineStage = 
  | 'validate'
  | 'detect'
  | 'select'
  | 'extract'
  | 'process'
  | 'finalize';

export interface PipelineContext {
  id: string;
  request: ExtractionRequest;
  platform: Platform;
  selectedProviders: string[];
  currentProvider?: string;
  attempts: ProviderAttempt[];
  result?: ExtractionResult;
  error?: Error;
  startTime: Date;
  endTime?: Date;
  stage: PipelineStage;
  metadata: Record<string, unknown>;
}

export interface ProviderAttempt {
  providerId: string;
  providerName: string;
  startTime: Date;
  endTime?: Date;
  success: boolean;
  error?: string;
  latencyMs?: number;
  result?: ExtractionResult;
}

// ─── Plugin ────────────────────────────────────────────────────────
export type PluginHook =
  | 'beforeExtract'
  | 'afterExtract'
  | 'onError'
  | 'onSuccess'
  | 'onProviderSelect'
  | 'onProviderFail'
  | 'onProviderFallback'
  | 'onCacheHit'
  | 'onCacheMiss'
  | 'onRateLimit'
  | 'onHealthCheck'
  | 'onRequest'
  | 'onResponse';

export interface PluginManifest {
  id: string;
  name: string;
  version: string;
  description?: string;
  author?: string;
  homepage?: string;
  hooks: PluginHook[];
  provides?: Platform[];
  dependencies?: string[];
}

export interface IPlugin {
  manifest: PluginManifest;
  install(context: PluginContext): void;
  uninstall?(): void;
}

export interface PluginContext {
  engine: unknown; // NovaDLEngine reference
  config: Record<string, unknown>;
  logger: unknown; // NovaLogger reference
  on(hook: PluginHook, handler: PluginHookHandler): void;
  off(hook: PluginHook, handler: PluginHookHandler): void;
  registerProvider(provider: unknown): void;
  getProvider(id: string): unknown | undefined;
}

export type PluginHookHandler = (context: PipelineContext, ...args: unknown[]) => unknown | Promise<unknown>;

// ─── Cache ─────────────────────────────────────────────────────────
export interface CacheEntry<T = ExtractionResult> {
  key: string;
  value: T;
  createdAt: Date;
  expiresAt?: Date;
  hits: number;
  tags?: string[];
  checksum?: string;
}

export interface ICacheAdapter {
  get<T>(key: string): Promise<CacheEntry<T> | null>;
  set<T>(key: string, value: T, ttlMs?: number, tags?: string[]): Promise<void>;
  delete(key: string): Promise<boolean>;
  clear(): Promise<void>;
  has(key: string): Promise<boolean>;
  size(): Promise<number>;
  getByTag(tag: string): Promise<CacheEntry[]>;
}

// ─── Queue ──────────────────────────────────────────────────────────
export type QueuePriority = 'critical' | 'high' | 'normal' | 'low';

export interface QueueJob<T = ExtractionRequest> {
  id: string;
  data: T;
  priority: QueuePriority;
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;
  attempts: number;
  maxAttempts: number;
  status: 'pending' | 'active' | 'completed' | 'failed' | 'retrying';
  error?: string;
  result?: ExtractionResult;
}

export interface IQueueAdapter {
  enqueue<T>(data: T, priority?: QueuePriority): Promise<QueueJob<T>>;
  dequeue(): Promise<QueueJob | null>;
  complete(jobId: string, result?: ExtractionResult): Promise<void>;
  fail(jobId: string, error?: string): Promise<void>;
  retry(jobId: string): Promise<void>;
  size(): Promise<number>;
  pending(): Promise<number>;
  active(): Promise<number>;
  clear(): Promise<void>;
  onCompleted(handler: (job: QueueJob) => void): void;
  onFailed(handler: (job: QueueJob) => void): void;
}

// ─── Rate Limit ────────────────────────────────────────────────────
export interface RateLimitEntry {
  key: string;
  count: number;
  windowStart: Date;
  blocked: boolean;
}

export interface IRateLimitAdapter {
  check(key: string): Promise<RateLimitResult>;
  increment(key: string): Promise<void>;
  reset(key: string): Promise<void>;
  clear(): Promise<void>;
  gc?(): number;
}

export interface RateLimitResult {
  allowed: boolean;
  remaining: number;
  resetAt: Date;
  total: number;
}

// ─── Metrics ────────────────────────────────────────────────────────
export interface EngineMetrics {
  extractions: {
    total: number;
    successful: number;
    failed: number;
    cached: number;
    fallbackUsed: number;
  };
  providers: Record<string, ProviderMetrics>;
  performance: {
    avgLatencyMs: number;
    p50LatencyMs: number;
    p95LatencyMs: number;
    p99LatencyMs: number;
    avgQueueWaitMs: number;
  };
  system: {
    uptimeMs: number;
    memoryUsageMb: number;
    activeConnections: number;
    queueSize: number;
  };
}

export interface ProviderMetrics {
  totalRequests: number;
  successfulRequests: number;
  failedRequests: number;
  avgLatencyMs: number;
  p50LatencyMs: number;
  p95LatencyMs: number;
  lastUsedAt?: Date;
  lastErrorAt?: Date;
  healthStatus: ProviderStatus;
}

// ─── Configuration ──────────────────────────────────────────────────
export interface NovaDLConfig {
  server: ServerConfig;
  providers: ProviderConfig[];
  cache: CacheConfig;
  queue: QueueConfig;
  security: SecurityConfig;
  extraction: ExtractionConfig;
  monitoring: MonitoringConfig;
  plugins: PluginConfig;
  custom?: Record<string, unknown>;
}

export interface ServerConfig {
  port: number;
  host: string;
  logLevel: 'trace' | 'debug' | 'info' | 'warn' | 'error' | 'fatal' | 'silent';
  debug: boolean;
  cors: {
    enabled: boolean;
    origins: string[];
  };
}

export interface CacheConfig {
  adapter: 'memory' | 'redis' | 'file' | 'custom';
  ttlMs: number;
  maxEntries: number;
  redisUrl?: string;
  filePath?: string;
}

export interface QueueConfig {
  adapter: 'memory' | 'redis' | 'custom';
  concurrency: number;
  redisUrl?: string;
}

export interface SecurityConfig {
  rateLimit: {
    max: number;
    windowMs: number;
  };
  maxUrlLength: number;
  ssrfBlockedHosts: string[];
  requestSigning: {
    enabled: boolean;
    secret?: string;
  };
  abuseDetection: {
    enabled: boolean;
    threshold: number;
    windowMs: number;
  };
}

export interface ExtractionConfig {
  defaultTimeoutMs: number;
  maxRetries: number;
  retryBackoffMs: number;
  parallelProviderTests: boolean;
  streamBufferSize: number;
  ytdlpPath: string;
  ytdlpTimeoutMs: number;
}

export interface MonitoringConfig {
  healthCheckIntervalMs: number;
  metricsEnabled: boolean;
  profilingEnabled: boolean;
}

export interface PluginConfig {
  directory?: string;
  autoLoad: boolean;
  enabledPlugins?: string[];
  disabledPlugins?: string[];
}

// ─── Events ─────────────────────────────────────────────────────────
export type EngineEvent =
  | 'extraction:start'
  | 'extraction:success'
  | 'extraction:fail'
  | 'extraction:cache_hit'
  | 'extraction:cache_miss'
  | 'provider:select'
  | 'provider:attempt'
  | 'provider:success'
  | 'provider:fail'
  | 'provider:fallback'
  | 'provider:health_change'
  | 'queue:enqueue'
  | 'queue:complete'
  | 'queue:fail'
  | 'plugin:install'
  | 'plugin:uninstall'
  | 'security:rate_limit'
  | 'security:abuse_detected'
  | 'security:ssrf_blocked';

// ─── API Types ─────────────────────────────────────────────────────
export interface ApiExtractionRequest {
  url: string;
  platform?: Platform;
  extractVideo?: boolean;
  extractAudio?: boolean;
  extractCover?: boolean;
  extractThumbnail?: boolean;
  extractMetadata?: boolean;
  extractSubtitles?: boolean;
  extractAllQualities?: boolean;
  detectWatermark?: boolean;
  removeWatermark?: boolean;
  preferredProvider?: string;
  preferredQuality?: string;
  preferredFormat?: MediaFormat;
  noFallback?: boolean;
  noCache?: boolean;
  stream?: boolean;
  formats?: MediaFormat[];
  qualities?: string[];
  languages?: string[];
  timeout?: number;
}

export interface ApiExtractionResponse {
  success: boolean;
  data?: ExtractionResult;
  error?: {
    code: string;
    message: string;
    provider?: string;
    attempts?: number;
  };
  meta: {
    requestId: string;
    latencyMs: number;
    providerUsed: string;
    cached: boolean;
    fallbackUsed: boolean;
  };
}

export interface ApiHealthResponse {
  status: 'healthy' | 'degraded' | 'unhealthy';
  uptime: number;
  version: string;
  providers: Record<string, ProviderHealth>;
  system: {
    memory: number;
    cpu: number;
    activeExtractions: number;
    queueSize: number;
  };
}

export interface ApiProvidersResponse {
  providers: ProviderInfo[];
}

export interface ProviderInfo {
  id: string;
  name: string;
  type: ProviderType;
  enabled: boolean;
  priority: number;
  platforms: Platform[];
  capabilities: ProviderCapabilities;
  health: ProviderHealth;
}

export interface ApiMetricsResponse {
  metrics: EngineMetrics;
}

export interface ApiErrorResponse {
  statusCode: number;
  error: string;
  message: string;
  requestId?: string;
  details?: unknown;
}
